### PR TITLE
Version 0.4.0 rework

### PR DESCRIPTION
**Pull request by mTsBucy1**
I have improved the ergonomics and documentation of this crate. This is obviously a breaking change and I have thus bumped the version to 0.4.0. After your review of #12 I've changed some more stuff.

I'm open to discussion to any change I've made, discussion can only lead to better code.

* The client now takes `ToSocketAddrs` as a address
* Preferred the use of `&str` arguments over String for ergonomics
* The client can now execute multiple commands. See #12 
* The client now connects in the constructor. See https://github.com/Miyoshi-Ryota/async-ssh2-tokio/issues/12 for the disucssion
* Every public types should now have documentation
* Some more tests where added, the docs test are now compile only
* Tests can now also be run locally without docker by setting environment variables
* The Error type was renamed to fit the ecosystem style
* Reexport the common types in the top level module
* The readme was updated with links to the docs
* This is a breaking change from 0.3.0 and previous 0.4.0 commits

### CODE REVIEW

**Comment by mTsBucy1** [comment]
Before you upload this to crates.io, let me continue using (and thus testing) this version for maybe a week to see if there are any fatal flaws in my rework.

**Review by Miyoshi-Ryota — APPROVED** [review]

**Comment by Miyoshi-Ryota** [comment]
@mTsBucy1 
I've already reviewed your amazing work! Personally, it looks like it is already ready to be released, as it appears to be working perfectly. (And if any issues are found, as long as they are fixed right away, that's fine.)

However, I will respect your decision and await your release decision. If you decide that we can release this version to crate.io as well, please mentions me again. I will release it immediately.

**Comment by mTsBucy1** [comment]
Like I kinda expected, I've found a major flaw: Seemingly after 10 commands, the ssh session disconnects (Tested on two different hosts, every time the 11th command fails). This, combined with the sometimes unreliable ssh connections, suggests we should implement automatic reconnection for robustness. I will probably look into it this week, but for now it's better not to merge yet.

**Comment by mTsBucy1** [comment]
Like I mentioned in #12 I've implemented authentication on every execute invocation. This is essentially how it was prior to my work, but now the calling `connect` is no longer necessary.

Also, for some reason the workflow test spuriously fail.

Again, please consider this a draft/beta release. I wouldn't want to pollute crates.io index with broken versions.

**Comment by mTsBucy1** [comment]
Sadly, because of different problems with ssh on windows, I don't plan on using this crate anymore.

I still consider the current version usable and in my option it can be merged & released. I don't know why some tests in the CI spuriously fail, on my local machine the tests always work. This not something I am able to spend time on to debug right now.

Thanks for your support

**Comment by Miyoshi-Ryota** [comment]
@mTsBucy1 
Okay! Thank you for your hard work! I'll fix rest of the problems, failure of thousands_commands test and some tests in CI, and merge it and release it on weekend!

**Pull request merged**
