### PR TITLE
fix ServerCheckMethod::KnownHosts with domain names

### PR DESCRIPTION
**Pull request by cybersoulK**
changes the signature of connect and connect_with_config

### CODE REVIEW

**Comment by cybersoulK** [comment]
@Miyoshi-Ryota i am bad at github so bare with me.

@cybersoulK
[preserve original hostname](https://github.com/Miyoshi-Ryota/async-ssh2-tokio/pull/41/commits/95247912318c876e238e4192bedab007b7800d21) changes the signature significantly but it's the cleanest method.
[ops, typo fix](https://github.com/Miyoshi-Ryota/async-ssh2-tokio/pull/41/commits/1df219dce07c57b7cc52be717c430bfb27eb0bd5) this one creates a custom trait to that it doesn't break anybody's code

**Comment by Miyoshi-Ryota** [comment]
@cybersoulK 
I'm at work now, so I'll check later. I'll probably check this weekend.

> i am bad at github so bare with me.

I haven't seen the content of the PR yet, but I'll just reply to this comment for now.

There's no need to worry about it at all. Everyone is not used to GitHub at first. 
I greatly appreciate your contribution and willingness to contribute.

**Comment by Miyoshi-Ryota** [comment]
# overall comments
@cybersoulK 

Sorry for the late reply. I did review your PR.
This patch is basically very nice and elegant. I love this patch very much. Thank you for your work.

Is it possible to make some minor fixes below?

1. Fixes to a outdated documentation
2. Apply linter
3. Add test cases for this usecase

If there are difficult matters for you to do, please let me know that. (If so, I will make additional commits after merging this PR and before releasing it. For example, I think this repo's test are tricky a little. )

## Fixes to a outdated documentation

The document of Client::connect method is outdated.
Could you updated this?
```
    /// [`ToSocketAddrs`] trait can be supplied for the address; see this trait
    /// documentation for concrete examples.
```

## Apply linter
Could you apply following linters and formatter? (see also CI error.)

- cargo fmt
- cargo clippy

## Add test cases for this usecase
Could you added test cases which tests KnownHostsFile with domain and IP?

**Review by Miyoshi-Ryota — COMMENTED** [review]
# overall comments
@cybersoulK 

Sorry for the late reply. I did review your PR.
This patch is basically very nice and elegant. I love this patch very much. Thank you for your work.

Is it possible to make some minor fixes below?

1. Fixes to a outdated documentation
2. Apply linter
3. Add test cases for this usecase

If there are difficult matters for you to do, please let me know that. (If so, I will make additional commits after merging this PR and before releasing it. For example, I think this repo's test are tricky a little. )

## Fixes to a outdated documentation

The document of Client::connect method is outdated.
Could you updated this?
```
    /// [`ToSocketAddrs`] trait can be supplied for the address; see this trait
    /// documentation for concrete examples.
```

## Apply linter
Could you apply following linters and formatter? (see also CI error.)

- cargo fmt
- cargo clippy

## Add test cases for this usecase
Could you added test cases which tests KnownHostsFile with domain and IP?

**Comment by cybersoulK** [comment]
I updated the docs, and run cargo fmt and cargo clippy. I cannot run the tests, and i am not sure how to test a domain name

**Comment by Miyoshi-Ryota** [comment]
@cybersoulK 
Thank you a lot! I've merged this PR.

>  I cannot run the tests, and I am not sure how to test a domain name

However, I'll release your work on crate.io after I add a test case for this PR. So please wait a little while for release. ( It may take 1-2days)

**Comment by Miyoshi-Ryota** [comment]
@cybersoulK 
I have already published🚀 your work as 0.8.0 to crates.io!

see also: 
https://crates.io/crates/async-ssh2-tokio

**Pull request merged**
